### PR TITLE
Update JShrink for php73 support

### PR DESCRIPTION
**Pull request by tkuther**
Note: requires namespaces

### CODE REVIEW

**Comment by samwilson** [comment]
I wonder if there's any chance of Piwigo using Composer, and loading JShrink from [tedivm/jshrink](https://packagist.org/packages/tedivm/jshrink)?

(I did try adding composer.json in #895, only for dev requirements, but there's been no movement on that front.)

**Comment by Teatek** [comment]
There is a problem for this issue because the required PHP version for JShrink 1.3.1 is 5.6 and piwigo 2.9.4 only require 5.3 or newer.
Would it be possible to isolate the specific change for this issue ?

**Comment by tkuther** [comment]
Why keep support for PHP versions that EOL'ed years ago? Even 5.6 is EOL meanwhile.

**Comment by plegall** [comment]
PR has already been updated. I close this PR

**Pull request closed without merging**
