### PR TITLE
Switch if-statement for readability.

### PR DESCRIPTION
**Pull request by lennartbecker**

### CODE REVIEW

**Comment by plegall** [comment]
Hi @lennartbecker 

The `if ('value' == $var)` is perfectly written "on purpose". Why is that? because if you write `if ($var == 'value')` you may write `if ($var = 'value')` by mistake and this will always be true... Instead if you write `if ('value' = $var)` by mistake you will immediately get an error.

**Comment by samwilson** [comment]
https://en.wikipedia.org/wiki/Yoda_conditions

**Comment by samwilson** [comment]
I imagine the intention is that all applicable conditionals in Piwigo will one day conform to that style. But software is always a _process_... :-)

**Comment by plegall** [comment]
>  But why is it only written like that sometimes?

As far as you read code I wrote, it should always be in "yoda" style :-) but I'm far from being the only one who code Piwigo!

**Comment by samwilson** [comment]
Maybe this PR should be changed to update the non-yoda style conditionals?

**Pull request closed without merging**
