### PR TITLE
Generate tif thumbnail, issue 324

### PR DESCRIPTION
**Pull request by Philippe-M**

### CODE REVIEW

**Comment by moy** [comment]
> Oups ne pas tenir compte du commit fe9877a

It's still time to `git push --force` into the branch for which you made the pull-request (`Philippe-M:master`) to delete the commit from the pull-request. Something like this should do the trick:

    git push --force origin 23dcde8:master

This pushes local commit 23dcde8 to remote branch `master`.

(Note: it's a good idea to create one branch per pull-request in your repository, this way you can easily update a PR without touching others)

**Comment by Philippe-M** [comment]
ok except for the commit comment that I can not change.

**Comment by moy** [comment]
You can still change everything (`git commit --amend` and `git push --force`) before the PR is merged.

Not saying that you *should* (that is not my decision to take), but you *can* ;-).

My 2 cents,

**Comment by Philippe-M** [comment]
Delete this, it's ok on 2.8. 

Thanks

**Pull request closed without merging**
