### PR TITLE
Initial work to support PHP 7.2

### PR DESCRIPTION
**Pull request by Infern1**
Fixes for create_function and each()

See #812

##TODO

- [x] Upgrade Smarty see https://github.com/smarty-php/smarty/pull/399 
- [x] Replace create_function (not done for mysql since not supported in PHP7)
- [ ] Replace each()
- [x] Upgrade cssmin with https://github.com/natxet/CssMin

### CODE REVIEW

**Comment by plegall** [comment]
Hi @Infern1 

Very good start, thank you!

When you write:

`$cat_map_callback = function($m) use ($cat_map) {  return $cat_map[$m[1]]["rank"]; };`

What is the minimum PHP version required for this to work?

**Comment by nikrou** [comment]
I think PHP 5.3 is required :
http://php.net/manual/en/functions.anonymous.php

**Comment by Infern1** [comment]
I update my php72 branch with the latest release 2.9.3, seems to work ok

**Comment by plegall** [comment]
@Infern1 why did you merge branch 2.9 ?

Considering you update Smarty, it's 99% sure this pull-request won't be merged on branch 2.9 but on master, and you should stick to branch master for your merge.

Actually I understand why you did that (to be able to use your fork on your production website), but that makes very complicated (or impossible) to merge this PR on Piwigo master :-/

**Comment by Infern1** [comment]
The reason I did merge 2.9.3 since I did not see any commits on master. However I did look on my own forked master branch which I did not bring in sync... so it was my own failure here.

I got the message today that there was a new release, so I thought merge those changes in. I will revert my merge with the 2.9.3 release

**Comment by Infern1** [comment]
sync again with master

**Comment by samwilson** [comment]
There seem to be a few places (outside of the Smarty files) where things are indented with tabs rather than two spaces.

**Comment by Infern1** [comment]
> There seem to be a few places (outside of the Smarty files) where things are indented with tabs rather than two spaces.

Easy fix ;)

**Comment by Infern1** [comment]
- [ ] No clue how to rewrite this one https://github.com/Piwigo/Piwigo/blob/8a57d777aa3b6401d74817822e0988fc4eb4a679/include/functions_search.inc.php#L126

- [ ]  mystery for me https://github.com/Piwigo/Piwigo/blob/8a57d777aa3b6401d74817822e0988fc4eb4a679/include/template.class.php#L1105

**Comment by nikrou** [comment]
```
function(&$s) { $s = '('.$s.')';}
```
and
```
function($matches) { eval('$tmp='.$matches[1].';');return $tmp; }, 
```
The "eval" is still a problem for me.

**Comment by Infern1** [comment]
implemented some more.
eval function is still supported so need to change at this moment

**Comment by plegall** [comment]
Considering this issue, Piwigo 2.10 will require PHP 5.3 (which is fine, everybody should be using an even more recente version of PHP). Or even PHP 5.4, see #867

**Comment by andrewjs18** [comment]
@plegall, when is 2.10 expected to be out?  currently for those of us using php 7.2 (probably the default version for newer versions of linux), our gallery is broken.  at least for me, using ubuntu 16.04, I cannot upload photos to my gallery whatsoever.

**Comment by plegall** [comment]
@andrewjs18 I can't tell you yet. If it was just a little patch, we would merge it to 2.9 and we would release 2.9.4 in a few days. But it's more important, with the Smarty upgrade.

On the other side, we have some new features to prepare/finish for 2.10 and I can only tell you it's impossible we release it in the upcoming weeks (to much work required).

I perfectly agree the incompatibility with PHP 7.2 is starting to be problematic to many users. I'm going to review the impact of changes (including Smarty) and see how I could merge it to 2.9.

**Comment by plegall** [comment]
Updating Smarty from 3.1.29 to 3.1.31 does not seem to be necessary to be compatible with PHP 7.2, as said on Smarty bugtracker : https://github.com/smarty-php/smarty/issues/383#issuecomment-338418745

@Infern1 is there a reason why you did update Smarty?

**Comment by plegall** [comment]
reply to myself:

> Deprecated: The each() function is deprecated. This message will be suppressed
> on further calls in include/smarty/libs/sysplugins/smarty_internal_compilebase.php
> on line 78

**Comment by plegall** [comment]
concerning Smarty, instead of updating all files, updating only smarty/libs/sysplugins/smarty_internal_compilebase.php seems to be enough (and would make the pull-request far shorter, which would be better)

**Comment by plegall** [comment]
Same thing for cssmin : I would prefer (in order to merge on Piwigo 2.9) to only have the required change, ie https://github.com/natxet/CssMin/commit/69b9a418b3020d61b89f572696db8035576ec45c (I have tested, it works fine)

**Comment by andrewjs18** [comment]
@plegall if you can get it into 2.9, that'll be great!  I've got a lot of photos waiting to be added to my gallery when it's compatible.

thanks!

**Comment by plegall** [comment]
(we will update Smarty and CSSmin, but not in order to be compatible with PHP 7.2, which is the focus on this pull-request)

**Comment by plegall** [comment]
@Infern1 I plan to release 2.9.4 next monday or tuesday (in 3 or 4 days). Do you think you will have simplified the fix on smarty and cssmin by this date?

**Comment by Infern1** [comment]
What is the reason to not update Smarty? I see also they fixed some security issues in Smarty. 

Also this is valid for cssmin? They did fix more then only php72 fixes. So why not getting all the fixes in? The main cssmin dev seams to be dead

**Comment by flop25** [comment]
it's a matter of time spend and breaking compatibilities
we would need to further test with probably a beta for such updates

**Comment by plegall** [comment]
To update Smarty to 3.1.32 and CSSmin, please create 2 other pull-requests :-) We will merge them on master for Piwigo 2.10 but not for 2.9

**Comment by Infern1** [comment]
ok clear

**Comment by Infern1** [comment]
Do we want the complete fix from Smarty which replaces each function

https://github.com/smarty-php/smarty/commit/30328d318c74dc28383fad997876276d4cd923ee#diff-01119648e7d724297400b231dad25064

**Comment by plegall** [comment]
@Infern1 in my test sooner this week, I have taken smarty/libs/sysplugins/smarty_internal_compilebase.php from Smarty 3.1.32 and it was running fine.

**Comment by andrewjs18** [comment]
thanks all for pushing this forward!

**Comment by Infern1** [comment]
>@Infern1 I plan to release 2.9.4 next monday or tuesday (in 3 or 4 days). Do you think you will have simplified the fix on smarty and cssmin by this date?
--

@plegall done

**Comment by plegall** [comment]
@Infern1 actually I meant simplifying this PR #834 (undo with a rollback commit https://github.com/Piwigo/Piwigo/pull/834/commits/db684f61516ae5471de18b22e7a30bf1c141efc4 and https://github.com/Piwigo/Piwigo/pull/834/commits/c8b12a2ed0edcd96223536ad5bbe3b4958dbe8fc) and make a new commit with only smarty_internal_compilebase.php changed and same for cssmin. I would like to be able to merge your PR.

If you can't do that, I that I will have to merge this PR on a specific new branch "php72", do the simplification myself then do a squash merge on master.

**Comment by Infern1** [comment]
I did create two new features which are independent if this PR.
See:
https://github.com/Piwigo/Piwigo/pull/889
https://github.com/Piwigo/Piwigo/pull/888

this pull requests are from master branch and you can merge them in.

**Comment by PieterBreugelmans** [comment]
As a reference, adding the error message one gets when performing a new installation.

Deprecated: The each() function is deprecated. This message will be suppressed on further calls in D:\app\Apache24\htdocs\piwigo\install.php on line 36

This is already taking into account as per https://github.com/Piwigo/Piwigo/pull/834/commits/bb0fcc3a307adae8f813cb8ec3040108a69caab5

**Comment by plegall** [comment]
@Infern1 I have forked your forked repo, made the 2 reverts on branch php72 and pushed a PR on your forked repo. Once you have merged my PR on your forked repo, I will be able to merge your PR on the official repo :-) (doing the revert on your side would have been simpler)

**Comment by plegall** [comment]
I have merge this PR, after adding the 2 requested `git revert`, see 063711240ac9ea9ddb1420bdb8ed8ee316f643f5. Unfortunately, Github does not view this merge as a pull-request merge. I close this PR but it was merged :-)

**Comment by plegall** [comment]
@andrewjs18 Piwigo 2.9.4 is available, with PHP 7.2 compatibility :-)

**Comment by andrewjs18** [comment]
fantastic.  thank you, sir!

@plegall

**Pull request closed without merging**
