### PR TITLE
Dashboard: show current version

### PR DESCRIPTION
**Pull request by foreachthing**
Show current Piwigo version on dashboard.

### CODE REVIEW

**Comment by plegall** [comment]
Hi @foreachthing 

I'm not sure this is a good idea. In Piwigo 2.9 we have moved this info from admin dashboard to page [Administration > Tools > Maintenance]. I don't think it's a very useful information for users. I don't mean it's useless, it's just not very useful on dashboard. So unless you can prove me I'm wrong we're not going to merge this pull-request BUT if you think it's useful, I advise you to create a plugin :-)

**Comment by nikrou** [comment]
Another way to make everybody happy is to provide a way to hook the admin dashboard and allow plugin to add content on it.

**Comment by foreachthing** [comment]
@plegall : I could not find that information (what version I'm running) until I looked for the language string in all those files. Then I found it buried in [Administration > Tools > Maintenance]; as you mentioned. Since the _check-upgrade_ button/link is on the dashboard, _I_ find it most useful to display the current version at same place.

**Comment by plegall** [comment]
@nikrou that's already the case, admin dashboard, like any page in Piwigo can be "hooked" :-) I did it for Piwigo.com, with a specific item about subscription.

screenshot-2017-11-6 piwigo com demonstration piwigo administration
```

add_event_handler('loc_end_intro', 'pcom_intro', 60);
function pcom_intro()
{
  global $template, $page, $user, $conf;

  $template->set_prefilter('intro', 'pcom_intro_prefilter');

  if (isset($page['page']) and 'intro' == $page['page'])
  {
      // some code ...

      $period_end_countdown = time_between(time(), strtotime($period_end));

      $template->assign(
        array(
          'CUSTOMER_STATUS_LABEL' => $customer_status_label,
          'PERIOD_END' => format_date($period_end),
          'PERIOD_END_COUNTDOWN' => $period_end_countdown,
          )
        );
   }
}

function pcom_intro_prefilter($content, &$smarty)
{
  $search = '</div> {* .stat-boxes *}';

  $replacement = '
<a class="stat-box" href="admin.php?page=account_manage">
<i class="icon-key"></i>
<span class="number">{$PERIOD_END_COUNTDOWN}</span><span class="caption tiptip" title="{\'current state of your account: <strong>%s</strong> until %s, in %s\'|@translate|@sprintf:$CUSTOMER_STATUS_LABEL:$PERIOD_END:$PERIOD_END_COUNTDOWN}">{$CUSTOMER_STATUS_LABEL}</span>
</a>

</div> {* .stat-boxes *}';

  return str_replace($search, $replacement, $content);
}
```

**Comment by plegall** [comment]
@foreachthing I understand why you like to have this info. On the other side I don't want this page to be "overcrowded" with technical information. I think I would be OK to integrate this request with 2 conditions:

1. the Piwigo version number only shows up when mouse cursor is on the "check upgrade" link
2. the label is clearly "current version is 2.9.2" and not only "2.9.2"

**Comment by fredsherbet** [comment]
Just chiming in to agree with @foreachthing - I couldn't figure out how to find out the current version, until I googled for it, and found this open issue :P

The reason I wanted to know, is because I was being prompted to upgrade, and wasn't sure what I was upgrading from!

**Comment by plegall** [comment]
This PR won't be merged, we did it "another way" for Piwigo 2.10 : the version is next to the "check for upgrade" button on the [Administration > Tools > Maintenance] page.

**Pull request closed without merging**
