### PR TITLE
please fix this minor typo in &rarr;

### PR DESCRIPTION
**Pull request by marc-portier**
should not be %rarr;

### CODE REVIEW

**Comment by ddtddt** [comment]
Hi :-)

if you want help us to maintem NL translation, login on https://piwigo.org/translate/

**Comment by marc-portier** [comment]
where to register?

**Comment by ddtddt** [comment]
Hi :-)

on EN forum
https://piwigo.org/forum/

**Comment by marc-portier** [comment]
done, user: mpo
I suppose my current 'visitor' status lacks privileges to actually do something?

**Comment by marc-portier** [comment]
same fix added to 
https://piwigo.org/translate/edit.php?language=nl_NL&project=trunk_public

(and translated new missing sections while I was there)
hope this allows to do your magic :)

**Comment by plegall** [comment]
I close this pull-request. It has been corrected with the translation tool :-)

**Pull request closed without merging**
