### PR TITLE
Order by the field(s) used to find duplicates

### PR DESCRIPTION
**Pull request by samwilson**
When searching for duplicates, also sort the results by the
fields used to find the duplicates.

Refs #860

### CODE REVIEW

**Comment by samwilson** [comment]
@plegall I'm not sure if this is the best place for this order-by code, but it seemed possibly appropriate. What do you think?

**Comment by samwilson** [comment]
Gentle bump.

(I'm processing a bunch of duplicates from an import and would love to have this patch merged, if it's suitable.)

**Comment by samwilson** [comment]
I'd be happy to improve this patch if required.

**Comment by samwilson** [comment]
@plegall this PR is still valid for the current master branch. I think it'd be good to be able to sort duplicate photos side-by-side. (Sorry if I keep hassling. Feel free to close this if you're not interested.)

**Comment by plegall** [comment]
I fully agree with this PR, very nice small improvement :-)

**Comment by samwilson** [comment]
Thanks!

**Pull request merged**
