### PR TITLE
Fix mediatype for api json format

### LINKED ISSUE #1847: Piwigo API returns wrong mediatype
When using format=json on the api, the wrong mediatype is returned.
This causes a problem when using different frameworks in java since automatic decoding is not supported.

For example the following code snippet will return an exception:

```
ClientConfig clientConfig = new ClientConfig().register(GsonMessageBodyHandler.class);
Client client = ClientBuilder.newClient(clientConfig);
Response response = client.target("https://<hostname>")
   .path(String.format("ws.php"))
   .queryParam(FORMAT_JSON.getKey(), FORMAT_JSON.getValue())
   .queryParam(IMAGE_INFO.getKey(), IMAGE_INFO.getValue())
   .queryParam(IMAGE_ID, imageId)
   .request(MediaType.APPLICATION_JSON).get();
return response.readEntity(PiwigoResponse.class);
```

Will send a request url: `https://<hostname>/ws.php?format=json&method=pwg.images.getInfo&image_id=339`

And result in an exception: 
```
org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/plain;charset=utf-8, type=class <package>.PiwigoResponse, genericType=class <package>.PiwigoResponse.
```

### PR DESCRIPTION
**Pull request by mingan666**
Fix #1847 

Changes mediatype to application/json

### CODE REVIEW

**Comment by plegall** [comment]
Hi @mingan666 

Thank you for this pull-request. Why don't we immediately merge it, as it seems so obvious it's the right fix? Because we don't want to break third party applications which would rely on the current `text/plain` mediatype.

Related to #1107 #406 or #448

The question is for me : how to make things right with `application/json` but not break old third party apps relying on `text/plain`? Then you understand why it's not as easy as it seems :-/

**Comment by plegall** [comment]
(I closed this PR by mistake, sorry)

**Comment by mingan666** [comment]
Thanks for the explanation.

I understand your concern, but at the same time the current bug is causing problems for 3th party libraries that are not able to recognize the response as json.
Would it be possible to add an additional query parameter requesting the proper mediatype?

Not that good at php so I'm not sure how to implement such a solution...

**Comment by mingan666** [comment]
Quick look suggest it would be possible to add an additional format into `include/ws_init.inc.php` and `tools/ws.htm`.
As well as an additional class that could extend `include/ws_protocols/json_encoder.php`

Not the finast solution, but it gives users that want a correct mediatype that option, without breaking exiting integrations.
As I wrote above, not that good att php so I might be missing other parts that might need tweaking as well...

**Pull request closed without merging**
