### PR TITLE
PHP 8: check for type object before calling get_class()

### PR DESCRIPTION
**Pull request by erAck**
Otherwise get_class() throws fatal error.
Reported in https://piwigo.org/forum/viewtopic.php?id=31711

### CODE REVIEW

**Comment by erAck** [comment]
@plegall Not interested in merging this?

**Comment by erAck** [comment]
@MatthieuLP interested in merging this?

**Comment by nitro322** [comment]
Thanks, @erAck.  I stumbled across this while trying to figure out why I could no longer use digiKam to export photos to piwigo - REST authentication is broken on PHP 8.x without this patch.  Working great with.  Much appreciated.

**Comment by plegall** [comment]
What about using `if ($response instanceof PwgError)` instead?

**Comment by erAck** [comment]
Sure, that's better, done. Found additional two occurrences.

**Pull request merged**
