### PR TITLE
Add better support for HTTPS Piwigo installations

### PR DESCRIPTION
**Pull request by lcorbasson**
- in the WS self-documentation

### CODE REVIEW

**Comment by modus75** [comment]
Better use href and src="//... rather than hard-coded http or https. No?

**Comment by plegall** [comment]
I agree with @modus75 I think the src="// was created exactly for that. Can you make the test @lcorbasson and update your branch for the pull-request?

**Comment by mistic100** [comment]
Resolved with #391

**Comment by lcorbasson** [comment]
Thanks @modus75, @plegall, @mistic100!

**Pull request closed without merging**
