### PR TITLE
Use entire language code.

### PR DESCRIPTION
**Pull request by xppppp**
HTTP_ACCEPT_LANGUAGE="ko" would match "kok_IN" instead of correctly matching "ko_KR"

### CODE REVIEW

**Comment by plegall** [comment]
Function array dereferencing has been added in PHP 5.4 and Piwigo is currently (version 2.9) not requiring such a version but 5.2. We plan to increase the requirement to PHP 5.4 #867 for Piwigo 2.10 so I think we can merge this pull-request :-)

**Comment by xppppp** [comment]
I just noticed that this PR is still out there.  In any case, language codes aren't always two characters, per RFC3066 (https://tools.ietf.org/html/rfc3066 - which references https://www.loc.gov/standards/iso639-2/php/code_list.php)

**Comment by samwilson** [comment]
Here's another regex for pulling language info from there: https://github.com/Krinkle/intuition/blob/236b5b134e045a109f85901ce4f50e70894db9be/src/Util.php#L159 (that Intuition library is pretty good at handling languages well; I've used it in a few projects).

**Comment by plegall** [comment]
I close this pull-request since #1132 does a more in-depth job (and was just merged)

**Pull request closed without merging**
